# Generated by Django 3.0.8 on 2020-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_id',
            new_name='category',
        ),
    ]
